/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GoTimePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var isWin = process.platform === "win32";
var isMac = process.platform === "darwin";
var DEFAULT_SETTINGS = {
  gotimePath: "gotime",
  evidencePaths: ""
};
var GoTimePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerDomEvent(document, "click", (evt) => {
      const target = evt.target;
      const link = target.closest("a");
      if (!link)
        return;
      const href = link.getAttribute("href") || link.getAttribute("data-href");
      if (!href)
        return;
      console.log("GoTime click handler href:", href);
      if (href.startsWith("gotime://")) {
        evt.preventDefault();
        evt.stopPropagation();
        const rest = href.slice("gotime://".length);
        const qIdx = rest.indexOf("?");
        const pathPart = qIdx >= 0 ? rest.slice(0, qIdx) : rest;
        const query = qIdx >= 0 ? rest.slice(qIdx + 1) : "";
        const fileHref = query ? `file://${pathPart}#${query}` : `file://${pathPart}`;
        this.openWithGoTime(fileHref);
        return;
      }
      if (href.startsWith("file://")) {
        const resolved = this.resolveFilePath(href);
        const videoExtensions = [".mp4", ".mov", ".mkv", ".avi", ".webm", ".flv", ".wmv", ".m4v", ".vob", ".ts", ".mts", ".mpg", ".mpeg"];
        evt.preventDefault();
        evt.stopPropagation();
        if (videoExtensions.some((ext) => resolved.toLowerCase().endsWith(ext))) {
          const finalHref = href.includes("#t=") ? href : `${href}#t=0`;
          this.openWithGoTime(finalHref);
        } else {
          this.openWithDefault(resolved);
        }
        return;
      }
      if (!href.startsWith("http") && !href.startsWith("#")) {
        const dotIdx = href.lastIndexOf(".");
        const ext = dotIdx >= 0 ? href.slice(dotIdx).toLowerCase() : "";
        if (ext && ext !== ".md") {
          const fullHref = `file://${href}`;
          const resolved = this.resolveFilePath(fullHref);
          const videoExtensions = [".mp4", ".mov", ".mkv", ".avi", ".webm", ".flv", ".wmv", ".m4v", ".vob", ".ts", ".mts", ".mpg", ".mpeg"];
          evt.preventDefault();
          evt.stopPropagation();
          if (videoExtensions.some((ext2) => resolved.toLowerCase().endsWith(ext2))) {
            const finalHref = href.includes("#t=") ? fullHref : `${fullHref}#t=0`;
            this.openWithGoTime(finalHref);
          } else {
            this.openWithDefault(resolved);
          }
        }
      }
    }, true);
    this.addSettingTab(new GoTimeSettingTab(this.app, this));
    console.log("GoTime plugin loaded");
  }
  onunload() {
    console.log("GoTime plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  resolveFilePath(href) {
    if (href.startsWith("file:///~/") || href.startsWith("file://~/")) {
      const raw = href.startsWith("file:///~/") ? href.slice("file:///~/".length) : href.slice("file://~/".length);
      const hashIdx = raw.indexOf("#");
      const relPath = decodeURIComponent(hashIdx >= 0 ? raw.slice(0, hashIdx) : raw);
      const basePath = (this.settings.evidencePaths || "").replace(/[\/]+$/, "");
      return path.join(basePath, relPath);
    }
    const url = new URL(href);
    let pathname = decodeURIComponent(url.pathname);
    if (isWin && /^\/[A-Za-z]:/.test(pathname)) {
      pathname = pathname.slice(1);
    }
    return pathname;
  }
  openWithDefault(filePath) {
    console.log("GoTime opening with default handler:", filePath);
    let child;
    if (isWin) {
      child = (0, import_child_process.spawn)("cmd", ["/c", "start", "", filePath], {
        detached: true,
        stdio: "ignore"
      });
    } else if (isMac) {
      child = (0, import_child_process.spawn)("open", [filePath], {
        detached: true,
        stdio: "ignore"
      });
    } else {
      child = (0, import_child_process.spawn)("xdg-open", [filePath], {
        detached: true,
        stdio: "ignore"
      });
    }
    child.unref();
    child.on("error", (error) => {
      new import_obsidian.Notice(`GoTime error: ${error.message}`);
      console.error("GoTime open error:", error);
    });
  }
  // ----- Wall-clock overlay (h1) lookup -----
  // Mirrors the semantics of MDReader.istag in obsidian-sync:
  // - frontmatter.tags may be undefined, a string, or a string[]
  // - returns true only if ALL required tags are present.
  istag(frontmatter, required) {
    const raw = frontmatter == null ? void 0 : frontmatter.tags;
    let tags;
    if (typeof raw === "string") {
      tags = [raw];
    } else if (Array.isArray(raw)) {
      tags = raw.map(String);
    } else {
      tags = [];
    }
    return required.every((t) => tags.includes(t));
  }
  // Transform a video path into something `fid` can consume.
  // For portable links (/~/relative/path) we strip the /~/ prefix and pass
  // the relative path; `fid` will resolve it using the active evidence
  // profile (so it works even if the plugin's evidencePaths setting is
  // stale or points to an unmounted drive). Absolute paths are passed
  // through unchanged.
  pathForFid(filePath) {
    if (filePath.startsWith("/~/")) {
      return filePath.slice(3);
    }
    return filePath;
  }
  // Call the `fid` CLI to resolve a video path to its Evidence ID (e.g. "V096").
  // Returns null if `fid` is not installed, errors, or finds no match.
  resolveFid(videoPath) {
    var _a;
    const abs = this.pathForFid(videoPath);
    try {
      const homeDir = process.env.HOME || process.env.USERPROFILE || "";
      const uvBin = path.join(homeDir, ".local", "bin");
      const pathSep = isWin ? ";" : ":";
      const envPATH = `${uvBin}${pathSep}${(_a = process.env.PATH) != null ? _a : ""}`;
      const env = { ...process.env, PATH: envPATH };
      const res = (0, import_child_process.spawnSync)("fid", [abs], { env, encoding: "utf8", timeout: 3e3 });
      if (res.status === 0) {
        const id = (res.stdout || "").trim();
        if (id)
          return id;
      }
    } catch (e) {
      console.error("GoTime fid error:", e);
    }
    return null;
  }
  findEvidenceNote(videoPath) {
    var _a;
    const mdFiles = this.app.vault.getMarkdownFiles();
    const id = this.resolveFid(videoPath);
    if (id) {
      const byId = mdFiles.find((f) => f.basename === id);
      if (byId)
        return byId;
    }
    const base = path.basename(videoPath);
    const stem = base.replace(/\.[^.]+$/, "");
    return (_a = mdFiles.find((f) => f.basename === stem)) != null ? _a : null;
  }
  // Parse a frontmatter time value (number of seconds, or an HH:MM:SS[.sss]
  // string, or plain seconds as a string) into seconds. Mirrors the
  // hms_to_secs logic used across the gotime/obsidian-sync toolchain.
  hmsToSecs(val) {
    if (val == null)
      return null;
    if (typeof val === "number")
      return val;
    const s = String(val).trim();
    if (!s)
      return null;
    let sign = 1;
    let body = s;
    if (body.startsWith("-")) {
      sign = -1;
      body = body.slice(1);
    }
    let out = 0;
    for (const part of body.split(":")) {
      const n = parseFloat(part);
      if (Number.isNaN(n))
        return null;
      out = out * 60 + n;
    }
    return sign * out;
  }
  // Collect clip overlay segments from a clipped evidence note's frontmatter.
  // Each clip_<n>_in/out defines a media sub-range; clip_<n>_hora1 (present
  // only for synced clips) provides the wall-clock start. Returns null when
  // the note has no clip_* properties.
  collectClips(fm) {
    const numbers = /* @__PURE__ */ new Set();
    for (const key of Object.keys(fm)) {
      const m = /^clip_(\d+)_in$/.exec(key);
      if (m)
        numbers.add(parseInt(m[1], 10));
    }
    if (numbers.size === 0)
      return null;
    const chunks = [];
    for (const n of Array.from(numbers).sort((a, b) => a - b)) {
      const tin = this.hmsToSecs(fm[`clip_${n}_in`]);
      const tout = this.hmsToSecs(fm[`clip_${n}_out`]);
      if (tin == null || tout == null)
        continue;
      const h1 = this.hmsToSecs(fm[`clip_${n}_hora1`]);
      chunks.push(`${n},${tin},${tout},${h1 != null ? h1 : ""}`);
    }
    return chunks.length ? chunks.join(";") : null;
  }
  // Build the overlay CLI args for a video. Clipped files (any clip_*
  // property) get a per-clip --clips overlay; whole-file uniform files
  // (evidence+lock with sync_hora1) get a single --h1 clock.
  getOverlayArgs(videoPath) {
    var _a, _b;
    console.log("GoTime overlay lookup for:", videoPath);
    const file = this.findEvidenceNote(videoPath);
    console.log("GoTime evidence note \u2192", (_a = file == null ? void 0 : file.path) != null ? _a : null);
    if (!file)
      return [];
    const fm = (_b = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _b.frontmatter;
    console.log("GoTime frontmatter \u2192", fm);
    if (!fm)
      return [];
    if (!this.istag(fm, ["evidence"])) {
      console.log("GoTime not an evidence note \u2192 no overlay");
      return [];
    }
    const clips = this.collectClips(fm);
    if (clips) {
      console.log("GoTime clips \u2192", clips);
      return ["--clips", clips];
    }
    if (this.istag(fm, ["lock"]) && fm.sync_hora1 != null) {
      console.log("GoTime sync_hora1 \u2192", fm.sync_hora1);
      return ["--h1", String(fm.sync_hora1)];
    }
    return [];
  }
  openWithGoTime(href) {
    var _a, _b, _c;
    let filePath;
    let fragment;
    if (href.startsWith("file:///~/") || href.startsWith("file://~/")) {
      const raw = href.startsWith("file:///~/") ? href.slice("file://".length) : "/" + href.slice("file://".length);
      const hashIdx = raw.indexOf("#");
      if (hashIdx >= 0) {
        filePath = decodeURIComponent(raw.slice(0, hashIdx));
        fragment = raw.slice(hashIdx + 1);
      } else {
        filePath = decodeURIComponent(raw);
        fragment = "";
      }
    } else {
      const url = new URL(href);
      filePath = decodeURIComponent(url.pathname);
      if (isWin && /^\/[A-Za-z]:/.test(filePath)) {
        filePath = filePath.slice(1);
      }
      fragment = url.hash.slice(1);
    }
    const params = new URLSearchParams(fragment);
    const timeStr = (_a = params.get("t")) != null ? _a : "0";
    const rect = params.get("rect");
    const args = [filePath, timeStr];
    if (rect)
      args.push("--rect", rect);
    args.push(...this.getOverlayArgs(filePath));
    console.log("GoTime executing:", this.settings.gotimePath, args);
    const homeDir = process.env.HOME || process.env.USERPROFILE || "";
    const uvBin = path.join(homeDir, ".local", "bin");
    const pathSep = isWin ? ";" : ":";
    const envPATH = `${uvBin}${pathSep}${process.env.PATH}`;
    const env = {
      ...process.env,
      PATH: envPATH
    };
    if (!isWin) {
      env.DISPLAY = process.env.DISPLAY || ":0";
      env.XDG_RUNTIME_DIR = process.env.XDG_RUNTIME_DIR || `/run/user/${(_c = (_b = process.getuid) == null ? void 0 : _b.call(process)) != null ? _c : 1e3}`;
    }
    const child = (0, import_child_process.spawn)(this.settings.gotimePath, args, {
      env,
      detached: true,
      stdio: "ignore",
      shell: isWin
    });
    child.unref();
    child.on("error", (error) => {
      new import_obsidian.Notice(`GoTime error: ${error.message}`);
      console.error("GoTime error:", error);
    });
    child.on("spawn", () => {
      console.log("GoTime spawned successfully");
      new import_obsidian.Notice("\u{1F3AC} Opening video...");
    });
  }
};
var GoTimeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("GoTime command path").setDesc("Path to the gotime executable (use full path if not in PATH)").addText((text) => text.setPlaceholder("gotime").setValue(this.plugin.settings.gotimePath).onChange(async (value) => {
      this.plugin.settings.gotimePath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Evidence base path").setDesc("Base path for portable video links (file://~/...). Set to your local video root directory.").addText((text) => text.setPlaceholder(isWin ? "D:\\Videos" : "/home/user/Videos").setValue(this.plugin.settings.evidencePaths).onChange(async (value) => {
      this.plugin.settings.evidencePaths = value;
      await this.plugin.saveSettings();
    }));
  }
};
